### ISSUE TITLE
Instalation & Compilation

### ISSUE THREAD

**Issue by charga** [FSund/transient-pipeline-flow#1]
Yesterday I found this respoitory and immedite download in order to test.
I follow all the instructions and found 2 problems.
1. If compile within a MSYS2 MSYS console, appears the following
$ cmake -G "MSYS Makefiles" ..
CMake Error: Could not create named generator MSYS Makefiles
So I open an MSYS2 MYNGW console and all works ok.
2. Compiling the repository has error
Scanning dependencies of target test_runner
[ 48%] Building CXX object test/CMakeFiles/test_runner.dir/test_runner.cpp.obj
In file included from C:/msys64/home/Carlos/transient-pipeline-flow/test/test_runner.cpp:2:
C:/msys64/home/Carlos/transient-pipeline-flow/third_party/doctest/doctest.h: In copy constructor 'doctest::detail::ContextBuilder::ContextBuilder(doctest::detail::ContextBuilder&)':
C:/msys64/home/Carlos/transient-pipeline-flow/third_party/doctest/doctest.h:3852:83: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct doctest::detail::ContextBuilder::Chunk' with no trivial copy-assignment [-Werror=class-memaccess]
 3852 |                unsigned(int(sizeof(Chunk)) * DOCTEST_CONFIG_NUM_CAPTURES_ON_STACK));
      |                                                                                   ^
In file included from C:/msys64/home/Carlos/transient-pipeline-flow/test/test_runner.cpp:2:
C:/msys64/home/Carlos/transient-pipeline-flow/third_party/doctest/doctest.h:1507:34: note: 'struct doctest::detail::ContextBuilder::Chunk' declared here
 1507 |         struct DOCTEST_INTERFACE Chunk
      |                                  ^~~~~
cc1plus.exe: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test_runner.dir/build.make:83: test/CMakeFiles/test_runner.dir/test_runner.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1007: test/CMakeFiles/test_runner.dir/all] Error 2
make: *** [Makefile:115: all] Error 2

So, how can I continue? Have you tested on Linux? Or Visual Studio?

Thanks

**Comment by FSund** [comment]
MSYS2 MINGW64 is the correct shell to compile the program.

I get the same error when trying to compile just now on a fresh installation. You could try not building the tests while I try to fix it :)

    cmake -G"MSYS Makefiles" -DBUILD_TESTS=OFF ..
    cmake --build .

**Comment by FSund** [comment]
I found the error, and now everything should compile correctly. Some of the tests currently fail, so I've opened a new issue for them: #2
